# Generated by Django 5.2.5 on 2025-09-13 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CbacUser",
            fields=[
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "user_id",
                    models.BigAutoField(
                        db_column="user_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(db_column="username", max_length=150, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_column="email",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(db_column="password_hash", max_length=255),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True, db_column="user_type", max_length=20, null=True
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True, db_column="reference_id", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="status", max_length=20, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="created_at", default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, db_column="last_login", null=True),
                ),
                ("is_active", models.BooleanField(db_column="is_active", default=True)),
                ("is_staff", models.BooleanField(db_column="is_staff", default=False)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Accounts",
            fields=[
                ("account_id", models.IntegerField(primary_key=True, serialize=False)),
                ("account_type", models.CharField(max_length=30)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "Accounts",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Branches",
            fields=[
                ("branch_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch_name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Branches",
                "verbose_name_plural": "Branches",
                "db_table": "branches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerPhotos",
            fields=[
                ("photo_id", models.FloatField(primary_key=True, serialize=False)),
                ("photo", models.BinaryField(blank=True, null=True)),
                ("uploaded_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Customer Photos",
                "verbose_name_plural": "Customer Photos",
                "db_table": "customer_photos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("email", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateField(blank=True, null=True)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("National ID", "National ID"),
                            ("Voter ID", "Voter ID"),
                            ("Passport", "Passport"),
                        ],
                        default="National ID",
                        max_length=50,
                    ),
                ),
                ("id_number", models.CharField(max_length=50, unique=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Active", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Customers",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DmlAuditLog",
            fields=[
                ("log_id", models.FloatField(primary_key=True, serialize=False)),
                ("table_name", models.CharField(blank=True, max_length=50, null=True)),
                ("operation", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "primary_key_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("column_name", models.CharField(blank=True, max_length=50, null=True)),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("changed_by", models.CharField(blank=True, max_length=50, null=True)),
                ("changed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "action_description",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
            ],
            options={
                "verbose_name": "Dml Audit Log",
                "verbose_name_plural": "Dml Audit Log",
                "db_table": "dml_audit_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Admin", "Admin"),
                            ("Teller", "Teller"),
                            ("Customer_Service_Rep", "Customer Service Rep"),
                            ("Branch_Manager", "Branch Manager"),
                            ("Loan_Officer", "Loan Officer"),
                            ("Relationship_Manager", "Relationship Manager"),
                            ("IT_Support", "IT Support"),
                            ("Compliance_Officer", "Compliance Officer"),
                            ("Audit_Officer", "Audit Officer"),
                            ("Operations_Manager", "Operations Manager"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Terminated", "Terminated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("terminated_on", models.DateField(blank=True, null=True)),
                (
                    "termination_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Employees",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ErrorLogs",
            fields=[
                ("log_id", models.FloatField(primary_key=True, serialize=False)),
                ("error_code", models.FloatField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                (
                    "module_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Error Logs",
                "verbose_name_plural": "Error Logs",
                "db_table": "error_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanActivityLogs",
            fields=[
                ("log_id", models.FloatField(primary_key=True, serialize=False)),
                ("loan_id", models.FloatField()),
                ("action_type", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=4000, null=True),
                ),
                ("performed_by", models.FloatField(blank=True, null=True)),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("module", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Loan Activity Logs",
                "verbose_name_plural": "Loan Activity Logs",
                "db_table": "loan_activity_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanDisbursementLog",
            fields=[
                ("log_id", models.FloatField(primary_key=True, serialize=False)),
                (
                    "disbursed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("disbursed_on", models.DateField(blank=True, null=True)),
                ("reversed_on", models.DateField(blank=True, null=True)),
                ("reversal", models.CharField(blank=True, max_length=1, null=True)),
                ("action_type", models.CharField(blank=True, max_length=20, null=True)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reversal_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Loan Disbursement Log",
                "verbose_name_plural": "Loan Disbursement Log",
                "db_table": "loan_disbursement_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoanRepayments",
            fields=[
                ("repayment_id", models.FloatField(primary_key=True, serialize=False)),
                ("due_date", models.DateField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "penalty_applied",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
            ],
            options={
                "verbose_name": "Loan Repayments",
                "verbose_name_plural": "Loan Repayments",
                "db_table": "loan_repayments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Loans",
            fields=[
                ("loan_id", models.IntegerField(primary_key=True, serialize=False)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("disbursed", models.CharField(blank=True, max_length=1, null=True)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Loans",
                "verbose_name_plural": "Loans",
                "db_table": "loans",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoginLogs",
            fields=[
                ("log_id", models.FloatField(primary_key=True, serialize=False)),
                ("user_id", models.FloatField(blank=True, null=True)),
                ("login_time", models.DateTimeField(blank=True, null=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("session_duration", models.DurationField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Login Logs",
                "verbose_name_plural": "Login Logs",
                "db_table": "login_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                ("history_id", models.FloatField(primary_key=True, serialize=False)),
                ("user_id", models.FloatField(blank=True, null=True)),
                ("old_password_hash", models.CharField(max_length=100)),
                ("new_hash", models.CharField(blank=True, max_length=100, null=True)),
                ("changed_by", models.FloatField()),
                ("changed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Password History",
                "verbose_name_plural": "Password History",
                "db_table": "password_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                ("permission_id", models.FloatField(primary_key=True, serialize=False)),
                ("permission_name", models.CharField(max_length=100)),
                ("module", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Permissions",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoleAssignmentAudit",
            fields=[
                ("audit_id", models.FloatField(primary_key=True, serialize=False)),
                ("admin_user_id", models.FloatField()),
                ("target_user_id", models.FloatField()),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Role Assignment Audit",
                "verbose_name_plural": "Role Assignment Audit",
                "db_table": "role_assignment_audit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RolePermissions",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "role_id",
                        "permission_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permissions",
                "verbose_name_plural": "Role Permissions",
                "db_table": "role_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("role_id", models.IntegerField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Roles",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Salaries",
            fields=[
                ("salary_id", models.FloatField(primary_key=True, serialize=False)),
                ("employee_id", models.FloatField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paid", models.DateField(blank=True, null=True)),
                ("paid_for_month", models.DateField()),
                (
                    "payment_month",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "verbose_name": "Salaries",
                "verbose_name_plural": "Salaries",
                "db_table": "salaries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureHistory",
            fields=[
                (
                    "structure_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("employee_id", models.FloatField()),
                ("base_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Salary Structure History",
                "verbose_name_plural": "Salary Structure History",
                "db_table": "salary_structure_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryStructures",
            fields=[
                ("structure_id", models.FloatField(primary_key=True, serialize=False)),
                ("base_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "deduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name": "Salary Structures",
                "verbose_name_plural": "Salary Structures",
                "db_table": "salary_structures",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "source_account",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "destination_account",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("reversal_of", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Transactions",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionStatusAudit",
            fields=[
                ("audit_id", models.FloatField(primary_key=True, serialize=False)),
                ("transaction_id", models.FloatField(blank=True, null=True)),
                ("old_status", models.CharField(blank=True, max_length=20, null=True)),
                ("new_status", models.CharField(blank=True, max_length=20, null=True)),
                ("changed_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Transaction Status Audit",
                "verbose_name_plural": "Transaction Status Audit",
                "db_table": "transaction_status_audit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("user_role_id", models.FloatField(primary_key=True, serialize=False)),
                ("assigned_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_role",
                "managed": False,
            },
        ),
    ]
